spring:
  datasource:
    url: jdbc:mysql://db:3306/dadokim
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    hikari:
      initializationFailTimeout: 0   # DB 준비 안됐으면 계속 재시도
      connectionTimeout: 30000       # 30초까지 대기

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true