server:
  port: 8080

cors:
  allowed-origins: "http://localhost:5173"

# 카카오 REST API 키 주입
#kakao: rest-api-key: ${kakao.rest-api-key}\

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dadokim
    username: ${USER_NAME}
    password: ${USER_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

