#spring.application.name=dadokim
#
## MySQL #
#spring.datasource.url=jdbc:mysql://localhost:3306/OAuth2
#spring.datasource.username=${USER_NAME}
#spring.datasource.password=${USER_PASSWORD}
#
## JPA #
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dadokim
    username: ${USER_NAME}
    password: ${USER_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true