spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dadokim
    username: ${USER_NAME}
    password: ${USER_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}